from agency_swarm.tools import BaseTool
from pydantic import Field
from typing import Literal
import os
import json

class OnboardingTool(BaseTool):
    """
    Customizes the Ad Creator Agency based on client requirements and preferences.
    This tool collects all necessary information to personalize the agency for different clients.
    """

    # 1. Company Information
    company_name: str = Field(
        ...,
        description="Your company or brand name"
    )

    # 2. Video Generation Model
    video_generation_model: Literal[
        "sora-2", 
        "sora-2-pro",
        "veo-3.1-generate-preview",
        "veo-3.1-fast-generate-preview"
    ] = Field(
        "sora-2",
        description="Video generation model to use (Sora for OpenAI, Veo 3.1 for Google Gemini)."
    )

    # 3. Brand Guidelines
    visual_brand_guidelines: str = Field(
        ...,
        description="Visual style preferences and brand guidelines for video ads (include aesthetic, mood, colors, etc.)",
        json_schema_extra={"ui:widget": "textarea"},
    )

    def run(self):
        """Saves configuration to onboarding_config.py"""
        # Get the directory where this tool is located
        tool_dir = os.path.dirname(os.path.abspath(__file__))
        config_path = os.path.join(tool_dir, "onboarding_config.py")

        # Convert tool fields to dictionary
        config = self.model_dump()

        # Convert to Python code format
        json_str = json.dumps(config, indent=4)
        json_str = json_str.replace(': null', ': None').replace(': true', ': True').replace(': false', ': False')
        python_code = f"""# Auto-generated configuration from OnboardingTool
# This file is generated by running: python onboarding_tool.py
# Do not edit manually - regenerate using the onboarding tool

config = {json_str}
"""

        # Write to file (with error handling for read-only filesystems)
        try:
            with open(config_path, "w", encoding="utf-8") as f:
                f.write(python_code)
            
            return f"Configuration saved to {config_path}\n\nNext steps:\n1. Review the generated config\n2. Set up your .env file with API keys (see .env.example)\n3. Run 'python agency.py' to start using your customized agency"
        
        except (PermissionError, OSError) as e:
            # If we can't write (e.g., in read-only container during schema extraction), just return success
            # The deployment system only needs the tool schema, not the actual file
            return f"Tool executed successfully (filesystem is read-only: {str(e)})"

# Test the tool with default values
if __name__ == "__main__":
    tool = OnboardingTool(
        # Using defaults from current repository
        company_name="[not provided by client]",
        video_generation_model="sora-2",
        visual_brand_guidelines="[not provided by client]",
    )
    print(tool.run())

