from agency_swarm.tools import BaseTool
from pydantic import Field
from typing import Literal, Optional
import os
import json

class OnboardingTool(BaseTool):
    """
    Customizes the Ad Creator Agency based on client requirements and preferences.
    This tool collects all necessary information to personalize the agency for different clients.
    """

    # 1. Company/Brand Information
    company_name: str = Field(
        "Your Company",
        description="Your company or brand name"
    )
    
    industry: str = Field(
        "E-commerce",
        description="Your industry or market vertical (e.g., E-commerce, SaaS, Health & Wellness, Finance)"
    )
    
    brand_voice: str = Field(
        "Professional yet approachable, authentic, and customer-focused",
        description="Description of your brand voice and tone",
        json_schema_extra={"ui:widget": "textarea"},
    )

    # 2. Target Audience
    target_audience_demographics: str = Field(
        "Adults 25-45, middle to upper-middle class, tech-savvy, value convenience and quality",
        description="Primary customer demographics (age, income, location, etc.)",
        json_schema_extra={"ui:widget": "textarea"},
    )
    
    target_audience_psychographics: str = Field(
        "Health-conscious, busy professionals seeking solutions that save time, value authenticity over flashy marketing, active on social media",
        description="Customer psychographics (values, lifestyle, behaviors, pain points)",
        json_schema_extra={"ui:widget": "textarea"},
    )

    # 3. Product Category
    product_category: str = Field(
        "Consumer Products",
        description="Type of products/services you're advertising (e.g., Consumer Products, Digital Services, B2B Software, Health Supplements)"
    )
    
    product_description: str = Field(
        "High-quality products that solve specific customer problems with innovative approaches",
        description="Brief overview of your products/services",
        json_schema_extra={"ui:widget": "textarea"},
    )

    # 4. Business Goals
    primary_business_goal: str = Field(
        "Increase product sales and brand awareness through high-converting UGC-style video ads",
        description="Your primary marketing/business objective",
        json_schema_extra={"ui:widget": "textarea"},
    )
    
    secondary_goals: str = Field(
        "Build trust and credibility, establish unique positioning in the market, create scalable ad production system",
        description="Secondary goals and success metrics (optional)",
        json_schema_extra={"ui:widget": "textarea"},
    )

    # 5. Brand Guidelines
    visual_style_preferences: str = Field(
        "Authentic UGC aesthetic, natural lighting, relatable settings, minimal post-production to maintain authenticity",
        description="Visual style preferences for video ads (colors, mood, aesthetic)",
        json_schema_extra={"ui:widget": "textarea"},
    )
    
    brand_colors: Optional[str] = Field(
        None,
        description="Brand color palette (optional, e.g., '#FF5733, #3498DB, #2ECC71')",
        json_schema_extra={"ui:placeholder": "e.g., #FF5733, #3498DB"},
    )

    # 6. Video Generation Model
    video_generation_model: Literal[
        "sora-2", 
        "sora-2-pro",
        "veo-3.1-generate-preview",
        "veo-3.1-fast-generate-preview"
    ] = Field(
        "sora-2",
        description="Video generation model to use (Sora for OpenAI, Veo 3.1 for Google Gemini). The cost is "
    )

    # 7. Output Format Preferences
    script_format_preferences: str = Field(
        "Natural conversational flow, one sentence per line for easy readability, direct-to-camera style suitable for UGC videos",
        description="Preferred format for ad scripts",
        json_schema_extra={"ui:widget": "textarea"},
    )

    def run(self):
        """Saves configuration to onboarding_config.py"""
        # Get the directory where this tool is located
        tool_dir = os.path.dirname(os.path.abspath(__file__))
        config_path = os.path.join(tool_dir, "onboarding_config.py")

        # Convert tool fields to dictionary
        config = self.model_dump()

        # Convert to Python code format
        json_str = json.dumps(config, indent=4)
        json_str = json_str.replace(': null', ': None').replace(': true', ': True').replace(': false', ': False')
        python_code = f"""# Auto-generated configuration from OnboardingTool
# This file is generated by running: python onboarding_tool.py
# Do not edit manually - regenerate using the onboarding tool

config = {json_str}
"""

        # Write to file (with error handling for read-only filesystems)
        try:
            with open(config_path, "w", encoding="utf-8") as f:
                f.write(python_code)
            
            return f"Configuration saved to {config_path}\n\nNext steps:\n1. Review the generated config\n2. Set up your .env file with API keys (see .env.example)\n3. Run 'python agency.py' to start using your customized agency"
        
        except (PermissionError, OSError) as e:
            # If we can't write (e.g., in read-only container during schema extraction), just return success
            # The deployment system only needs the tool schema, not the actual file
            return f"Tool executed successfully (filesystem is read-only: {str(e)})"

# Test the tool with default values
if __name__ == "__main__":
    tool = OnboardingTool(
        # Using defaults from current repository
        company_name="Your Company",
        industry="E-commerce",
        brand_voice="Professional yet approachable, authentic, and customer-focused",
        target_audience_demographics="Adults 25-45, middle to upper-middle class, tech-savvy, value convenience and quality",
        target_audience_psychographics="Health-conscious, busy professionals seeking solutions that save time, value authenticity over flashy marketing, active on social media",
        product_category="Consumer Products",
        product_description="High-quality products that solve specific customer problems with innovative approaches",
        primary_business_goal="Increase product sales and brand awareness through high-converting UGC-style video ads",
        secondary_goals="Build trust and credibility, establish unique positioning in the market, create scalable ad production system",
        visual_style_preferences="Authentic UGC aesthetic, natural lighting, relatable settings, minimal post-production to maintain authenticity",
        brand_colors=None,
        video_generation_model="sora-2",
        script_format_preferences="Natural conversational flow, one sentence per line for easy readability, direct-to-camera style suitable for UGC videos",
    )
    print(tool.run())

