# Auto-generated configuration from OnboardingTool
# This file is generated by running: python onboarding_tool.py
# Do not edit manually - regenerate using the onboarding tool

config = {
    "company_name": "[not provided by client]",
    "sora_model": "sora-2",
    "veo_model": "veo-3.1-generate-preview",
    "visual_brand_guidelines": "[not provided by client]"
}
