import pprint
from typing import Literal

from pydantic import Field

from agency_swarm.tools import BaseTool


class OnboardingTool(BaseTool):
    """
    Customizes the Ad Creator Agency based on client requirements and preferences.
    This tool collects all necessary information to personalize the agency for different clients.
    """

    # 1. Company Information
    company_name: str = Field(..., description="Your company or brand name")

    # 2. Image Model Selection (Nano Banana)
    image_model: Literal["gemini-2.5-flash-image-preview", "gemini-3-pro-image-preview"] = Field(
        "gemini-2.5-flash-image-preview",
        description=(
            "Select the image generation model.\n"
            "- gemini-2.5-flash-image-preview (Nano Banana): Standard model\n"
            "- gemini-3-pro-image-preview (Nano Banana Pro): New, higher quality model (recommended)\n"
        ),
    )

    # 3. Sora Model Selection (for b-rolls and new characters)
    sora_model: Literal["sora-2", "sora-2-pro"] = Field(
        "sora-2",
        description=(
            "Select the Sora model version for b-rolls, new characters, and general video generation.\n"
            "- sora-2 (recommended for testing): $0.10/second\n"
            "- sora-2-pro (recommended for production): $0.30/second\n"
        ),
    )

    # 4. Brand Guidelines
    visual_brand_guidelines: str = Field(
        ...,
        description="Visual style preferences and brand guidelines for video ads (include aesthetic, mood, colors, etc.)",
        json_schema_extra={"ui:widget": "textarea"},
    )

    # 5. Brand Assets
    brand_assets: list[str] = Field(
        [],
        description="Upload your brand assets for video ads here (for example: logos, product images, product descriptions). Only images (PNG, JPG) and PDFs are supported at this time. Please use clear, descriptive filenames such as 'logo.png', 'product_image.jpg', or 'product_description.pdf' to help the agent use each asset appropriately.",
        json_schema_extra={
            "x-file-upload-path": "./brand_assets",
        },
    )

    def run(self):
        """Saves configuration to onboarding_config.py"""
        # Resolve to the agency root: ugc_agent/tools/OnboardingTool.py -> ad_factory/
        from pathlib import Path

        agency_root = Path(__file__).resolve().parent.parent.parent
        config_path = str(agency_root / "onboarding_config.py")

        # Convert tool fields to dictionary
        config = self.model_dump()

        # Convert to Python code format
        python_code = f"""# Auto-generated configuration from OnboardingTool
# This file is generated by running: python onboarding_tool.py
# Do not edit manually - regenerate using the onboarding tool

config = {pprint.pformat(config, indent=4)}
"""

        # Write to file (with error handling for read-only filesystems)
        try:
            with open(config_path, "w", encoding="utf-8") as f:
                f.write(python_code)

            return f"Configuration saved to {config_path}\n\nNext steps:\n1. Review the generated config\n2. Set up your .env file with API keys (see .env.example)\n3. Run 'python agency.py' to start using your customized agency"

        except (PermissionError, OSError) as e:
            # If we can't write (e.g., in read-only container during schema extraction), just return success
            # The deployment system only needs the tool schema, not the actual file
            return f"Tool executed successfully (filesystem is read-only: {str(e)})"


# Test the tool with default values
if __name__ == "__main__":
    tool = OnboardingTool(
        # Using defaults from current repository
        company_name="[not provided by client]",
        image_model="gemini-3-pro-image-preview",
        sora_model="sora-2",
        visual_brand_guidelines="[not provided by client]",
        brand_assets=[],
    )
    print(tool.run())
